version: '2'
name: todo-list

services:
  client:
    build: ./app
    image: ghcr.io/merosya/todo-list/todo-list:latest
    ports:
      - "3000:3000"
    networks:
      todo-list-network:
        ipv4_address: 10.0.0.2

  server:
    build: ./server
    image: ghcr.io/merosya/todo-list/todo-list-server:latest
    ports:
      - "8080:8080"
    networks:
      todo-list-network:
        ipv4_address: 10.0.0.3
  
networks:
  todo-list-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1