name: docker image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the app Docker image
      uses: docker/build-push-action@v2
      with:
          context: ./app
          tags: |
            ghcr.io/merosya/todo-list/todo-list:latest
          push: ${{ github.ref == 'refs/heads/main' }}

    - name: Build and push the app Docker image
      uses: docker/build-push-action@v2
      with:
          context: ./server
          tags: |
            ghcr.io/merosya/todo-list/todo-list-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}
